### ISSUE TITLE
3-phase router with single phase water heater

### ISSUE THREAD

**Issue by philippesikora** [FredM67/mk2pvrouter#1]
Thank you for this optimized 3-phase mk2pvrouter firmware. Very impressive
I would like to use this optimized firmware to divert on single phase water heater only from 3-phase network. The router should divert surplus of energy to this single water heater (highest priority) from 0% to 100%, then to the second resistive load (0% to 100%) and finally to the third. Can you set up a setting to get this extra feature ?
Thank you
Philippe

**Comment by FredM67** [comment]
Hi Philippe,

Thx 😉
Well, what you need is in fact the "original" feature of Robin's sketch. Except that the original sketch doesn't fully run with the ISR, so that data-logging for example can disturb the router functionality itself.
I'll modify my version with a couple of defines, so that if you for example don't need to take care of peak/off-peak period or priority rotation or so, you can simply enable/disable it at the beginning of the sketch, so it's done for the temperature support.
Please give me a couple of days to do the changes... with luck, I'll get it in 1-2 days.

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : philippesikora <notifications@github.com>
Envoyé : jeudi 19 décembre 2019 11:12
À : FredM67/mk2pvrouter <mk2pvrouter@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [FredM67/mk2pvrouter] 3-phase router with single phase water heater (#1)


Thank you for this optimized 3-phase mk2pvrouter firmware. Very impressive
I would like to use this optimized firmware to divert on single phase water heater only from 3-phase network. The router should divert surplus of energy to this single water heater (highest priority) from 0% to 100%, then to the second resistive load (0% to 100%) and finally to the third. Can you set up a setting to get this extra feature ?
Thank you
Philippe

**Comment by philippesikora** [comment]
Hi Fred,
Yes, right. If D5 is unable to consume all surplus power, D6 and then D7 will automatically be activated.
The prime purpose of the Mk2 Router is to measure real power. As your sketch runs with the ISR, the calculation of additional parameters such as apparent power (P_app) and power factor (cos_phi = P_rms / P_app) could be now possible. What do you think ? It will be a great extra feature -:)
Philippe

**Comment by FredM67** [comment]
Well, for apparent power over the 3 phases, I simply read the data sent by the official counter since I don't need real time values (done with an ESP8266). For the power factor, I think I get it too from the main counter.
It's for sure interesting to know about these values, but I don't think it's really useful except for much bigger installations with a lot of motors and such things.

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : philippesikora <notifications@github.com>
Envoyé : jeudi 19 décembre 2019 12:26
À : FredM67/mk2pvrouter <mk2pvrouter@noreply.github.com>
Cc : FredM67 <frederic.metrich@live.fr>; Comment <comment@noreply.github.com>
Objet : Re: [FredM67/mk2pvrouter] 3-phase router with single phase water heater (#1)


Hi Fred,
Yes, right. If D5 is unable to consume all surplus power, D6 and then D7 will automatically be activated.
The prime purpose of the Mk2 Router is to measure real power. As your sketch runs with the ISR, the calculation of additional parameters such as apparent power (P_app) and power factor (cos_phi = P_rms / P_app) could be now possible. What do you think ? It will be a great extra feature -:)
Philippe

**Comment by philippesikora** [comment]
Hi Fred. Thank you, it make sense. You don't need extra features like P_app and cos_phi.
By default, your firmware is running ANTI-FLICKER mode and REQUIRED_EXPORT_IN_WATTS=10 
Recommendation was to set REQUIRED_EXPORT_IN_WATTS=50, does it work well with 10W in France with 3-phase electronic meter and Linky ?
Philippe

**Comment by FredM67** [comment]
Well, I don't have any Linky at home, and since I've installed the router, it's just working perfectly, with 10W export. The meter installed is a Landis&Gyr model zmd 126 in 3-phase version.
It could be that my system works with this setting because each load has a max power of 1kW.

Fred

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by FredM67** [comment]
Hi,

I've just made the change so off-peak (w/o rotation) can be disable in the sketch.
Please let me know if it's ok for you...

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : philippesikora <notifications@github.com>
Envoyé : jeudi 19 décembre 2019 16:23
À : FredM67/mk2pvrouter <mk2pvrouter@noreply.github.com>
Cc : FredM67 <frederic.metrich@live.fr>; Comment <comment@noreply.github.com>
Objet : Re: [FredM67/mk2pvrouter] 3-phase router with single phase water heater (#1)


Hi Fred. Thank you, it make sense. You don't need extra features like P_app and cos_phi.
By default, your firmware is running ANTI-FLICKER mode and REQUIRED_EXPORT_IN_WATTS=10
Recommendation was to set REQUIRED_EXPORT_IN_WATTS=50, does it work well with 10W in France with 3-phase electronic meter and Linky ?
Philippe

**Comment by philippesikora** [comment]
Hi Fred. I performed some test and it looks loadPrioritiesAndState[1] is always ON.
I added only serial print in the loop as follows:

Serial.print(loadPrioritiesAndState[0]);
Serial.print(loadPrioritiesAndState[1]);
Serial.print(loadPrioritiesAndState[2]);
A@

**Comment by FredM67** [comment]
Hi,

I don't think so.
Each item contains 2 "values". You've to make some logical operations to read what you want to know.
On default, the load priorities are simply:

  *   1st load with highest,
  *   2nd load with "medium"
  *   3d load with lowest.

Then, the last bit of each item is the state of the load.
So, if loadPrioritiesAndState[0] is 0 then the load is off, if it's 128 (0x80 in hex) then it's on.
For the 2nd load it'll be 1 if off and 129 if on. And for the 3d, it'll be 2 or 130.

Now, suppose you set the load priority to first load 3, then load 2 and then load 1....
You'll get:

  *   loadPrioritiesAndState[0] with 2 or 130
  *   loadPrioritiesAndState[1] with 1 or 129
  *   loadPrioritiesAndState[2] with 2 or 128.

Item #0 is always the first load to be switch on, then item #1 and finally item #2.

See also comment between line 896 and line 907.

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : philippesikora <notifications@github.com>
Envoyé : lundi 23 décembre 2019 22:48
À : FredM67/mk2pvrouter <mk2pvrouter@noreply.github.com>
Cc : FredM67 <frederic.metrich@live.fr>; Comment <comment@noreply.github.com>
Objet : Re: [FredM67/mk2pvrouter] 3-phase router with single phase water heater (#1)


Hi Fred. I performed some test and it looks loadPrioritiesAndState[1] is always ON.
I added only serial print in the loop as follows:

Serial.print(loadPrioritiesAndState[0]);
Serial.print(loadPrioritiesAndState[1]);
Serial.print(loadPrioritiesAndState[2]);
A@

**Comment by philippesikora** [comment]
Thank you, I got it
 :-)

**Comment by FredM67** [comment]
It might be a little bit complicated if you're not used to use some things.
If this code would be for a bigger system (with more RAM, ...), I wouldn't have programmed it like this.
But since the memory of an Arduino or ESP01 or such system is quite small, I try to make things as much as possible in a "compact" way.

Have a good night...
Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : philippesikora <notifications@github.com>
Envoyé : lundi 23 décembre 2019 23:25
À : FredM67/mk2pvrouter <mk2pvrouter@noreply.github.com>
Cc : FredM67 <frederic.metrich@live.fr>; Comment <comment@noreply.github.com>
Objet : Re: [FredM67/mk2pvrouter] 3-phase router with single phase water heater (#1)


Thank you, I got it
:-)

**Comment by philippesikora** [comment]
Dear Fred, 
I commented out #define PRIORITY_ROTATION and your firmware is running fine since 2 weeks now with a specific data logging on serial IF (a WEMOS-D1 is connected to Rx/Tx with embedded web-server and OLED display). Thank you for this great firmware -:))
I would like to use OFF_PEAK_TARIFF option with my 3-phase Landis & Gyr model ZMD 126 and single phase hot boiler connected to load_0.
When OFF_PEAK_TARIFF starts, I would like to force load_0 only during 5 hours max by example.
May you update your firmware to choose at compilation which loads could be forced at OFF_PEAK_TARIFF ? Sorry to ask you this update but I don't want to break this firmware.
Thank you
Philippe

**Comment by FredM67** [comment]
Hi Philippe,
Are you located in France? Since you've the same meter as mine!
Ok no problem.. Let me a couple of days to do that.... Probably during the weekend I'll find some time.
Fred

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Hi Fred, please take your time, yes I'm located in south of France (Var).
A@

**Comment by FredM67** [comment]
Okay, then we could talk in French 😂
N'est-ce pas ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by FredM67** [comment]
Hi,

I think, I'm finished with the changes.
I'll update the source code today after work.
I didn't test it, I hope it'll work properly.
Please pick up the code from the "_try_" branch. As soon as you've validated the code (please let it run over 2-3 days), I'll merge it to the main branch.

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : philippesikora <notifications@github.com>
Envoyé : vendredi 3 janvier 2020 20:24
À : FredM67/mk2pvrouter <mk2pvrouter@noreply.github.com>
Cc : FredM67 <frederic.metrich@live.fr>; Comment <comment@noreply.github.com>
Objet : Re: [FredM67/mk2pvrouter] 3-phase router with single phase water heater (#1)


Hi Fred, please take your time, yes I'm located in south of France (Var).
A@

**Comment by FredM67** [comment]
You can download the code...

**Comment by philippesikora** [comment]
Bonjour Fred, merci pour la modification du code.

J'ai modifié à la compilation avec les constantes ci-dessous pour obtenir le résultat suivant:
Load_0 actif pendant 5h sans offset, Load_1 pas actif, Load_2 pas actif.  Est-ce la bonne méthode ?

***************
#ifdef OFF_PEAK_TARIFF
//#define PRIORITY_ROTATION                     
constexpr uint32_t ul_OFF_PEAK_DURATION{8ul};
constexpr uint32_t rg_ForceLoad[NO_OF_DUMPLOADS][2] = {{0, 5}, {0, 0}, {0, 0}};
**************

Merci, Philippe

**Comment by FredM67** [comment]
A priori, c'est la bonne méthode... Tu peux tester en forçant le off-peak... J'ai tout programmé en aveugle !

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Par contre, est-ce je peux relier directement la sortie relais du compteur Landis & Gyr ZMD126 ou bien une sortie relais 5V (qui provient d'un gestionnaire d'énergie) sur la broche PD3 sans danger pour le microcontroleur ? (problème de rebond et surtension transitoire  sur la broche PD3)

**Comment by FredM67** [comment]
[Image]

Oui, c'est ce que j'ai fait. Dans le compteur, c'est un simple interrupteur passif sans aucune tension. Le tout, c'est qu'il faut que ça soit passif. Pour forcer le tarif heures creuses, il suffit juste de court-circuiter les 2 pattes (extérieures) de D3.


Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by FredM67** [comment]
La tension est fournie par le microcontroller avec une résistance interne... Donc aucun danger...

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Je ne comprend pas bien comment cela fonctionne. Le compteur tri comporte 2 sorties C1 et C2.
Doit-on court-circuiter C1 et C2 et relier le tout à la broche N°5  (PD3) du microcontrôleur ?

**Comment by FredM67** [comment]
Tu branches une des pattes sur C1 et l'autre sur C2.
Cf. Doc jointe... [Image]
Sur la photo les deux câbles de droite sont relié à un ESP qui lit la télé-information et les deux câbles de gauche sont reliés aux deux pin D3.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by philippesikora** [comment]
A priori les photos ne passent pas. Peux-tu m'envoyer les photos sur mon email perso p.sikora@hotmail.fr ?

**Comment by philippesikora** [comment]
Merci j'ai reçu la photo.
Je comprend qu'il faut relier C1 et C2 sur les 2 pattes extérieures de D3.
Par contre je ne comprend encore pas le fonctionnement. La broche PD3 est en configuration sortie avec une résistance interne de pullup:

DDRD &= ~(1 << offPeakForcePin);               // set as output
PORTD |= (1 << offPeakForcePin);                 // enable the internal pullup resistor

Comment le compteur tri peut piloter le routeur dans cette configuration ?

**Comment by FredM67** [comment]
Lorsque le compteur passe en heures creuses, le relais interne entre C1 et C2 se ferme, du coup les 2 pin sont en "court-circuit"- soit résistance nulle et donc tension nulle. Quand tu lis la pin, elle passe de HIGH à LOW.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by FredM67** [comment]
En fait, mon commentaire erroné t'a embrouillé la tête, D3 est en input et non output. Un peu trop de copier-coller !
Je corrige demain...

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
J'ai enfin compris le fonctionnement. Merci.
Par contre j'ai envoyé le soft sur ta méssagerie perso. A priori le soft ne fonctionne pas correctement au niveau des valeurs de puissance active L1, L2 et L3

**Comment by FredM67** [comment]
Aie... Je regarde ça demain !
Tu as calibré ton système correctement ?
C'est très importante pour avoir des valeurs correctes et un fonctionnement correct.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Bien vu, j'ai toujours utilisé le mode NORMAL et non pas en mode ANTI-FLICKER.
Mon test précédent est en mode ANTI-FLICKER sans calibration.

Je fais un essai avec une compilation et téléversement en mode NORMAL et je te communique le résultat.
A@

**Comment by FredM67** [comment]
Il faut impérativement calibrer le système sinon ça ne fonctionne pas sauf coup de chance. Et sur le montage, il y a un petit bridge à ne surtout pas oublié, c'est pour ça que je souhaiterais une photo détaillée de ton montage...  quand j'ai soudé mes composants je l'avais oublié, les valeurs étaient à l'ouest, j'ai discuté avec Robin, on a cherché 2-3 jours et on a trouvé le pb... Ce fameux bridge !

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Bon même avec une compilation et téléversement en mode NORMAL, j'ai un affichage farfelu des puissances actives L1, L2 et L3

**Comment by FredM67** [comment]
Les valeurs f_powerCal sont très importantes, c'est dépendant des CTs (aucun n'est 100% identique), des transfo, de la tension de fonctionnement du microcontrolleur,...
Pour déterminer ces valeurs, il faut utiliser le sketch de calibrage.... Je peux t'expliquer si tu veux...

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Ton soft précédent en mode NORMAL fonctionne parfaitement sur la platforme triphasé.

**Comment by FredM67** [comment]
Bizarre je vérifie demain si j'ai pas merdé quelque part....

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by philippesikora** [comment]
Je regarde aussi si je n'ai pas fait de mauvaise modification
